'use strict';

/**
 * Generate the small root-level text files that have to stay in step with the
 * page list and the origin: robots.txt, llms.txt, the IndexNow key file, and
 * /.well-known/apple-app-site-association.
 *
 * All four are committed; this script just keeps them from drifting when a page
 * is added to scripts/site.config.js.
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { ROOT, ORIGIN, PAGES, APP, url } = require('./site.config.js');

const written = [];
function write(rel, body) {
  const file = path.join(ROOT, rel);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, body);
  written.push([rel, Buffer.byteLength(body)]);
}

// ------------------------------------------------------------- robots.txt

function robots() {
  // AI crawlers are listed explicitly rather than left to the wildcard: several
  // of them treat "no named group" as ambiguous, and being cited by an assistant
  // is worth as much to this site as a blue link.
  const aiAgents = [
    ['GPTBot', 'OpenAI — ChatGPT browsing and training'],
    ['OAI-SearchBot', 'OpenAI — ChatGPT search index'],
    ['ChatGPT-User', 'OpenAI — user-initiated page fetches'],
    ['ClaudeBot', 'Anthropic — Claude'],
    ['anthropic-ai', 'Anthropic — legacy agent name'],
    ['Claude-Web', 'Anthropic — legacy agent name'],
    ['PerplexityBot', 'Perplexity'],
    ['Google-Extended', 'Google — Gemini / AI Overviews grounding'],
    ['CCBot', 'Common Crawl'],
    ['Applebot-Extended', 'Apple Intelligence'],
    ['Amazonbot', 'Amazon'],
    ['meta-externalagent', 'Meta AI']
  ];

  const lines = [
    '# DollarSeeds — https://dollarseeds.app',
    '# Generated by scripts/gen-static.js.',
    '',
    '# Every standard crawler: the whole site is public and indexable.',
    'User-agent: *',
    'Allow: /',
    '',
    '# AI crawlers and answer engines, allowed explicitly.',
    ''
  ];

  for (const [agent, why] of aiAgents) {
    lines.push('# ' + why);
    lines.push('User-agent: ' + agent);
    lines.push('Allow: /');
    lines.push('');
  }

  lines.push('Sitemap: ' + url('/sitemap.xml'));
  lines.push('');
  return lines.join('\n');
}

// --------------------------------------------------------------- llms.txt

function llms() {
  // Follows the llms.txt convention: an H1 name, a blockquote summary, prose,
  // then H2 sections of linked resources with one-line descriptions.
  const section = (title, items) =>
    '## ' + title + '\n\n' +
    items.map(p => '- [' + p.path + '](' + url(p.path) + '): ' + p.blurb).join('\n') + '\n';

  const isLesson = p => p.path.startsWith('/lessons');
  const isLegal = p => ['/privacy', '/terms', '/cookie-policy', '/delete-account'].includes(p.path);
  const core = PAGES.filter(p => !isLesson(p) && !isLegal(p));

  return [
    '# DollarSeeds',
    '',
    '> DollarSeeds is a Christian budgeting app for iPhone that splits every dollar of income',
    '> across Needs, Wants, and Savings automatically, with no bank login required. It tracks',
    '> spending against each bucket, funds savings goals and debt payoff, and teaches money',
    '> through Scripture-rooted lessons.',
    '',
    'The app ships three budgeting types, all of which save at least 20% of income:',
    '',
    '- **50/30/20** — 50% Needs, 30% Wants, 20% Savings. The balanced default.',
    '- **Wealth Builder** — 30% Needs, 20% Wants, 50% Savings. For strong incomes and small fixed costs.',
    '- **Firm Foundation** — 70% Needs, 10% Wants, 20% Savings. For tight seasons, without giving up the savings floor.',
    '',
    'Free on the App Store, iOS only, released 2026-08-07. Built by ' + APP.author + '.',
    'App Store listing: ' + APP.storeUrl,
    '',
    section('Core pages', core),
    section('Lessons', PAGES.filter(isLesson)),
    section('Legal and account', PAGES.filter(isLegal)),
    '## Optional',
    '',
    '- [Download](' + url('/download') + '): redirects to the App Store listing.',
    ''
  ].join('\n');
}

// ------------------------------------- apple-app-site-association (universal links)

function aasa() {
  const appID = APP.appleTeamId + '.' + APP.bundleId;
  return JSON.stringify({
    applinks: {
      // `details` replaces the deprecated top-level `apps` key; an empty
      // `apps: []` is no longer required by any supported iOS version.
      details: [
        {
          appIDs: [appID],
          components: [
            // Deep-link the marketing and content pages into the app where an
            // equivalent screen exists, and let the rest open in Safari.
            { '/': '/', comment: 'Home' },
            { '/': '/lessons', comment: 'Lessons index' },
            { '/': '/lessons/*', comment: 'Individual lessons' },
            { '/': '/50-30-20-rule', comment: 'Budgeting guide' },
            { '/': '/budgeting-types', comment: 'Budgeting types guide' },
            { '/': '/download', comment: 'App Store redirect' },
            { '/': '/privacy', exclude: true, comment: 'Legal pages stay in the browser' },
            { '/': '/terms', exclude: true, comment: 'Legal pages stay in the browser' },
            { '/': '/cookie-policy', exclude: true, comment: 'Legal pages stay in the browser' },
            { '/': '/delete-account', exclude: true, comment: 'Account deletion stays in the browser' }
          ]
        }
      ]
    },
    webcredentials: { apps: [appID] }
  }, null, 2) + '\n';
}

// -------------------------------------------------------------- IndexNow

/**
 * The IndexNow key is a stable 32-hex-character token. It is derived from the
 * origin so it regenerates identically rather than changing on every run — a
 * rotating key would invalidate the key file the search engines fetch.
 */
function indexNowKey() {
  return crypto.createHash('sha256').update('indexnow:' + ORIGIN).digest('hex').slice(0, 32);
}

function main() {
  write('robots.txt', robots());
  write('llms.txt', llms());
  write('.well-known/apple-app-site-association', aasa());

  const key = indexNowKey();
  write(key + '.txt', key + '\n');

  for (const [file, bytes] of written) {
    console.log('  ' + file.padEnd(48) + String(bytes + ' B').padStart(8));
  }
  console.log('static: ' + written.length + ' files  ·  IndexNow key ' + key);
}

main();
