'use strict';

/**
 * Generate sitemap.xml from the page list in site.config.js, and keep the
 * <lastmod> honest.
 *
 * lastmod resolution, best source first:
 *   1. the file's last git commit date — correct even on a fresh checkout,
 *      where every mtime is the clone time
 *   2. the value already in sitemap.xml — a shallow clone may not carry the
 *      commit that last touched a file, and a stale-but-real date beats
 *      stamping every page with today's build time
 *   3. the filesystem mtime
 *
 * It also rewrites `dateModified` in each lesson's Article JSON-LD from the
 * same resolved date, so the schema and the sitemap cannot disagree.
 */

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const { ROOT, PAGES, url } = require('./site.config.js');

const SITEMAP = path.join(ROOT, 'sitemap.xml');

/** ISO date (YYYY-MM-DD) of the last commit that touched `file`, or null. */
function gitDate(file) {
  try {
    const out = execFileSync('git', ['log', '-1', '--format=%cI', '--', file],
      { cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
    return out ? out.slice(0, 10) : null;
  } catch {
    return null;   // no git, or file never committed
  }
}

/** Previous <lastmod> values, keyed by absolute URL. */
function previousLastmod() {
  if (!fs.existsSync(SITEMAP)) return {};
  const xml = fs.readFileSync(SITEMAP, 'utf8');
  const out = {};
  const re = /<loc>([^<]+)<\/loc>\s*<lastmod>([^<]+)<\/lastmod>/g;
  let m;
  while ((m = re.exec(xml)) !== null) out[m[1]] = m[2];
  return out;
}

function resolveLastmod(page, previous) {
  const absolute = url(page.path);
  return gitDate(page.file)
    || previous[absolute]
    || new Date(fs.statSync(path.join(ROOT, page.file)).mtime).toISOString().slice(0, 10);
}

/** Keep each lesson's Article dateModified equal to its sitemap lastmod. */
function syncArticleDates(dates) {
  let updated = 0;
  for (const page of PAGES) {
    if (!page.file.startsWith('lessons/') || page.file.endsWith('index.html')) continue;

    const file = path.join(ROOT, page.file);
    let html = fs.readFileSync(file, 'utf8');
    const want = '"dateModified": "' + dates[page.path] + '"';
    const found = /"dateModified": "\d{4}-\d{2}-\d{2}"/.exec(html);
    if (!found) { console.warn('  no dateModified in ' + page.file); continue; }
    if (found[0] === want) continue;

    html = html.replace(found[0], want);
    fs.writeFileSync(file, html);
    updated++;
    console.log('  ' + page.file + ': dateModified -> ' + dates[page.path]);
  }
  return updated;
}

function main() {
  const previous = previousLastmod();
  const dates = {};
  for (const page of PAGES) dates[page.path] = resolveLastmod(page, previous);

  const body = PAGES.map(page =>
    '  <url>\n' +
    '    <loc>' + url(page.path) + '</loc>\n' +
    '    <lastmod>' + dates[page.path] + '</lastmod>\n' +
    '  </url>'
  ).join('\n');

  const xml =
    '<?xml version="1.0" encoding="UTF-8"?>\n' +
    '<!-- Generated by build/gen-sitemap.js. Do not edit by hand:\n' +
    '     add the page to PAGES in build/site.config.js instead. -->\n' +
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n' +
    '        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n' +
    '        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 ' +
    'http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">\n' +
    body + '\n' +
    '</urlset>\n';

  fs.writeFileSync(SITEMAP, xml);
  console.log('sitemap: ' + PAGES.length + ' URLs -> sitemap.xml');

  const synced = syncArticleDates(dates);
  if (synced) console.log('sitemap: synced dateModified on ' + synced + ' lesson page(s)');
}

main();
